// <auto-generated />
using System;
using FCUpgrade.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FCUpgrade.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260902152548_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FCUpgrade.Domain.Entities.BaitSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualDroppedToLevel")
                        .HasColumnType("integer");

                    b.Property<bool?>("ActualSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("BaitHistoryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConsecutiveFails")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FeedbackAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<double>("PredictedProbability")
                        .HasColumnType("double precision");

                    b.Property<string>("PredictedRiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer");

                    b.Property<double>("TargetBars")
                        .HasColumnType("double precision");

                    b.Property<int>("TargetFromLevel")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBaitCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalLevelsDropped")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActualSuccess");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TargetFromLevel");

                    b.ToTable("BaitSessions");
                });

            modelBuilder.Entity("FCUpgrade.Domain.Entities.ImportJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsInserted")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsReceived")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsRejected")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsUnchanged")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsUpdated")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ImportJobs");
                });

            modelBuilder.Entity("FCUpgrade.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameShort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FCUpgrade.Domain.Entities.PlayerSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Def")
                        .HasColumnType("integer");

                    b.Property<int>("Dri")
                        .HasColumnType("integer");

                    b.Property<int>("FootPref")
                        .HasColumnType("integer");

                    b.Property<string>("FootPrefString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FootWeak")
                        .HasColumnType("integer");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NationId")
                        .HasColumnType("integer");

                    b.Property<string>("NationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ovr")
                        .HasColumnType("integer");

                    b.Property<int>("Pac")
                        .HasColumnType("integer");

                    b.Property<int>("Pas")
                        .HasColumnType("integer");

                    b.Property<int>("Phy")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Pos1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pos2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PriceKr")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("Sho")
                        .HasColumnType("integer");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Traits")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.Property<string>("WorkRateAtt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkRateDef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("NationId");

                    b.HasIndex("Ovr");

                    b.HasIndex("Pos1");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.HasIndex("PlayerId", "SeasonId");

                    b.ToTable("PlayerSeasons");
                });

            modelBuilder.Entity("FCUpgrade.Domain.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeasonId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("SeasonId")
                        .IsUnique();

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("FCUpgrade.Domain.Entities.PlayerSeason", b =>
                {
                    b.HasOne("FCUpgrade.Domain.Entities.Player", "Player")
                        .WithMany("PlayerSeasons")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FCUpgrade.Domain.Entities.Season", "Season")
                        .WithMany("PlayerSeasons")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("FCUpgrade.Domain.Entities.Player", b =>
                {
                    b.Navigation("PlayerSeasons");
                });

            modelBuilder.Entity("FCUpgrade.Domain.Entities.Season", b =>
                {
                    b.Navigation("PlayerSeasons");
                });
#pragma warning restore 612, 618
        }
    }
}
